### PR TITLE
A fix and some additions

### PR DESCRIPTION
**Pull request by RawandKurdy**
- Fixed bug where project links were not working
- Added LinkedIn to the supported socials
- Added possiblity of customizing link text of projects (alias property added and is optional)

### CODE REVIEW

**Comment by RawandKurdy** [comment]
@hadisinaee I checked the latest release and the link issue still persists, why not merge?

**Comment by hadisinaee** [comment]
@RawandKurdy Ohh, I had seen your changes but forgotten to discuss and merge them! So I guess your pull request was deleted because I deleted the branch, not because of the changes you had made. 

Thanks for reminding 👍🏼

**Comment by RawandKurdy** [comment]
@hadisinaee using the theme personally, Thank you first, and would love to contribute

**Comment by hadisinaee** [comment]
@RawandKurdy That's very nice of you 👍🏼

**Pull request closed without merging**
